version: '2'
services:
  probot-app-workflow:
    build: .
    volumes:
      - .:/probot-app-workflow
      - /probot-app-workflow/node_modules/
    environment:
      - NOW_TOKEN
      - NOW_TEAM
      - ORG_LIST
      - GH_TOKEN
      - BUILDKITE
      - BUILDKITE_REPO
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
